[book]
authors =               # Enter author book here, example ["Đa Vương Nguyên"]
language =              # Enter language book here. Example English = "en", Vietnamese = "vi",...
multilingual = true
src = "src"
title =                 # Enter title book here, example "My Book"
text_direction = "ltr"

[build]
build-dir = "book"
create-missing = true
use-default-proccessors = true

[output.html]
mathjax-support = true