[book]
authors = ["Arthor Name"]
language = ["language"]
multilingual = true
src = "src"
title = ["Book Title"]
text_direction = "ltr"

[build]
build-dir = "book"
create-missing = true
use-default-proccessors = true
